apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: comfy-backend-api-pipeline
description: main application pipeline
serialPipeline:
  stages:
  - targetId: dev-comfy-backend
    profiles: [dev]
  - targetId: prod-comfy-backend
    profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-comfy-backend
description: Cloud Run development service
run:
  location: projects/dreamboothy/locations/us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-comfy-backend
description: Cloud Run production service
run:
  location: projects/dreamboothy/locations/us-central1