version: "3.8"

services:
  registry-backend:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app # Ensure this matches the working_dir
      - $HOME/.config/gcloud/application_default_credentials.json:/tmp/keys/application_default_credentials.json
    environment:
      DRIP_ENV: localdev
      DB_CONNECTION_STRING: "user=postgres password=postgres host=host.docker.internal port=54322 dbname=postgres"
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/application_default_credentials.json # This will be set in prod by GCP.
      GOOGLE_CLOUD_PROJECT: "dreamboothy-dev" # This will be set in prod by GCP.
      PROJECT_ID: "dreamboothy-dev"
      CORS_ORIGIN: "http://localhost:3000"
      JWT_SECRET: 8zT9YknYUTZRVAkgov86gT1NLezTtwrd # test secret
      LOG_LEVEL: info # Set the log level here
      ALGOLIA_APP_ID: 
      ALGOLIA_API_KEY: 
      SECRET_SCANNER_URL: ""
