# Prod Cloud Run

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: prod-comfy-backend
spec:
  template:
    spec:
      containers:
      - image: registry-backend-image-substitute
        env: 
        - name: DRIP_ENV
          value: staging
        - name: SELF_ORIGIN
          value: https://api.drip.art
        - name: APPROVED_ZONE
          value: us-central1-a,us-central1-b,us-central1-c,us-central1-f