steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--tag"
      - "gcr.io/$PROJECT_ID/comfyui-nodepack"
      - "."
    dir: node-pack-extract

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "run"
      - "--env"
      - "AUTO_UPDATE=true"
      - "--env"
      - "CUSTOM_NODE_URL=$_CUSTOM_NODE_URL"
      - "--env"
      - "CUSTOM_NODE_NAME=$_CUSTOM_NODE_NAME"
      - "--volume"
      - "/workspace:/workspace"
      - "--workdir"
      - "/workspace"
      - "gcr.io/$PROJECT_ID/comfyui-nodepack"
      - "$_CUSTOM_NODE_NAME.json"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - -c
      - gcloud auth print-identity-token --audiences="$_REGISTRY_BACKEND_URL" | tee /workspace/token
    waitFor: ["-"]

  - name: "badouralix/curl-jq"
    entrypoint: "sh"
    args:
      - -c
      - |
        jq -c '. += {"cloud_build_info": {
            "project_id": "$PROJECT_ID",
            "project_number": "$PROJECT_NUMBER",
            "location": "$LOCATION",
            "build_id": "$BUILD_ID"
          }}' "/workspace/$_CUSTOM_NODE_NAME.json" | tee "/workspace/curl-payload.json" 

        NODE="$(basename $(dirname $(dirname '$_CUSTOM_NODE_URL')))"
        VERSION="$(basename $(dirname '$_CUSTOM_NODE_URL'))"
        curl -vsS --fail-with-body \
          -H "Authorization: Bearer $(cat /workspace/token)" \
          -H "Content-Type: application/json" \
          -X "POST" "-d" "@/workspace/curl-payload.json" \
          "$_REGISTRY_BACKEND_URL/nodes/$$NODE/versions/$$VERSION/comfy-nodes"

substitutions:
  _CUSTOM_NODE_NAME: "default-node-name"
  _CUSTOM_NODE_URL: "https://example.com/default-node.tar.gz"
  _REGISTRY_BACKEND_URL: "https://echo.free.beeceptor.com"

options:
  logging: CLOUD_LOGGING_ONLY
