// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"registry-backend/ent/ciworkflowresult"
	"registry-backend/ent/gitcommit"
	"registry-backend/ent/predicate"
	"registry-backend/ent/storagefile"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CIWorkflowResultUpdate is the builder for updating CIWorkflowResult entities.
type CIWorkflowResultUpdate struct {
	config
	hooks     []Hook
	mutation  *CIWorkflowResultMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CIWorkflowResultUpdate builder.
func (cwru *CIWorkflowResultUpdate) Where(ps ...predicate.CIWorkflowResult) *CIWorkflowResultUpdate {
	cwru.mutation.Where(ps...)
	return cwru
}

// SetUpdateTime sets the "update_time" field.
func (cwru *CIWorkflowResultUpdate) SetUpdateTime(t time.Time) *CIWorkflowResultUpdate {
	cwru.mutation.SetUpdateTime(t)
	return cwru
}

// SetOperatingSystem sets the "operating_system" field.
func (cwru *CIWorkflowResultUpdate) SetOperatingSystem(s string) *CIWorkflowResultUpdate {
	cwru.mutation.SetOperatingSystem(s)
	return cwru
}

// SetNillableOperatingSystem sets the "operating_system" field if the given value is not nil.
func (cwru *CIWorkflowResultUpdate) SetNillableOperatingSystem(s *string) *CIWorkflowResultUpdate {
	if s != nil {
		cwru.SetOperatingSystem(*s)
	}
	return cwru
}

// SetGpuType sets the "gpu_type" field.
func (cwru *CIWorkflowResultUpdate) SetGpuType(s string) *CIWorkflowResultUpdate {
	cwru.mutation.SetGpuType(s)
	return cwru
}

// SetNillableGpuType sets the "gpu_type" field if the given value is not nil.
func (cwru *CIWorkflowResultUpdate) SetNillableGpuType(s *string) *CIWorkflowResultUpdate {
	if s != nil {
		cwru.SetGpuType(*s)
	}
	return cwru
}

// ClearGpuType clears the value of the "gpu_type" field.
func (cwru *CIWorkflowResultUpdate) ClearGpuType() *CIWorkflowResultUpdate {
	cwru.mutation.ClearGpuType()
	return cwru
}

// SetPytorchVersion sets the "pytorch_version" field.
func (cwru *CIWorkflowResultUpdate) SetPytorchVersion(s string) *CIWorkflowResultUpdate {
	cwru.mutation.SetPytorchVersion(s)
	return cwru
}

// SetNillablePytorchVersion sets the "pytorch_version" field if the given value is not nil.
func (cwru *CIWorkflowResultUpdate) SetNillablePytorchVersion(s *string) *CIWorkflowResultUpdate {
	if s != nil {
		cwru.SetPytorchVersion(*s)
	}
	return cwru
}

// ClearPytorchVersion clears the value of the "pytorch_version" field.
func (cwru *CIWorkflowResultUpdate) ClearPytorchVersion() *CIWorkflowResultUpdate {
	cwru.mutation.ClearPytorchVersion()
	return cwru
}

// SetWorkflowName sets the "workflow_name" field.
func (cwru *CIWorkflowResultUpdate) SetWorkflowName(s string) *CIWorkflowResultUpdate {
	cwru.mutation.SetWorkflowName(s)
	return cwru
}

// SetNillableWorkflowName sets the "workflow_name" field if the given value is not nil.
func (cwru *CIWorkflowResultUpdate) SetNillableWorkflowName(s *string) *CIWorkflowResultUpdate {
	if s != nil {
		cwru.SetWorkflowName(*s)
	}
	return cwru
}

// ClearWorkflowName clears the value of the "workflow_name" field.
func (cwru *CIWorkflowResultUpdate) ClearWorkflowName() *CIWorkflowResultUpdate {
	cwru.mutation.ClearWorkflowName()
	return cwru
}

// SetRunID sets the "run_id" field.
func (cwru *CIWorkflowResultUpdate) SetRunID(s string) *CIWorkflowResultUpdate {
	cwru.mutation.SetRunID(s)
	return cwru
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (cwru *CIWorkflowResultUpdate) SetNillableRunID(s *string) *CIWorkflowResultUpdate {
	if s != nil {
		cwru.SetRunID(*s)
	}
	return cwru
}

// ClearRunID clears the value of the "run_id" field.
func (cwru *CIWorkflowResultUpdate) ClearRunID() *CIWorkflowResultUpdate {
	cwru.mutation.ClearRunID()
	return cwru
}

// SetStatus sets the "status" field.
func (cwru *CIWorkflowResultUpdate) SetStatus(s string) *CIWorkflowResultUpdate {
	cwru.mutation.SetStatus(s)
	return cwru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cwru *CIWorkflowResultUpdate) SetNillableStatus(s *string) *CIWorkflowResultUpdate {
	if s != nil {
		cwru.SetStatus(*s)
	}
	return cwru
}

// ClearStatus clears the value of the "status" field.
func (cwru *CIWorkflowResultUpdate) ClearStatus() *CIWorkflowResultUpdate {
	cwru.mutation.ClearStatus()
	return cwru
}

// SetStartTime sets the "start_time" field.
func (cwru *CIWorkflowResultUpdate) SetStartTime(i int64) *CIWorkflowResultUpdate {
	cwru.mutation.ResetStartTime()
	cwru.mutation.SetStartTime(i)
	return cwru
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (cwru *CIWorkflowResultUpdate) SetNillableStartTime(i *int64) *CIWorkflowResultUpdate {
	if i != nil {
		cwru.SetStartTime(*i)
	}
	return cwru
}

// AddStartTime adds i to the "start_time" field.
func (cwru *CIWorkflowResultUpdate) AddStartTime(i int64) *CIWorkflowResultUpdate {
	cwru.mutation.AddStartTime(i)
	return cwru
}

// ClearStartTime clears the value of the "start_time" field.
func (cwru *CIWorkflowResultUpdate) ClearStartTime() *CIWorkflowResultUpdate {
	cwru.mutation.ClearStartTime()
	return cwru
}

// SetEndTime sets the "end_time" field.
func (cwru *CIWorkflowResultUpdate) SetEndTime(i int64) *CIWorkflowResultUpdate {
	cwru.mutation.ResetEndTime()
	cwru.mutation.SetEndTime(i)
	return cwru
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (cwru *CIWorkflowResultUpdate) SetNillableEndTime(i *int64) *CIWorkflowResultUpdate {
	if i != nil {
		cwru.SetEndTime(*i)
	}
	return cwru
}

// AddEndTime adds i to the "end_time" field.
func (cwru *CIWorkflowResultUpdate) AddEndTime(i int64) *CIWorkflowResultUpdate {
	cwru.mutation.AddEndTime(i)
	return cwru
}

// ClearEndTime clears the value of the "end_time" field.
func (cwru *CIWorkflowResultUpdate) ClearEndTime() *CIWorkflowResultUpdate {
	cwru.mutation.ClearEndTime()
	return cwru
}

// SetGitcommitID sets the "gitcommit" edge to the GitCommit entity by ID.
func (cwru *CIWorkflowResultUpdate) SetGitcommitID(id uuid.UUID) *CIWorkflowResultUpdate {
	cwru.mutation.SetGitcommitID(id)
	return cwru
}

// SetNillableGitcommitID sets the "gitcommit" edge to the GitCommit entity by ID if the given value is not nil.
func (cwru *CIWorkflowResultUpdate) SetNillableGitcommitID(id *uuid.UUID) *CIWorkflowResultUpdate {
	if id != nil {
		cwru = cwru.SetGitcommitID(*id)
	}
	return cwru
}

// SetGitcommit sets the "gitcommit" edge to the GitCommit entity.
func (cwru *CIWorkflowResultUpdate) SetGitcommit(g *GitCommit) *CIWorkflowResultUpdate {
	return cwru.SetGitcommitID(g.ID)
}

// SetStorageFileID sets the "storage_file" edge to the StorageFile entity by ID.
func (cwru *CIWorkflowResultUpdate) SetStorageFileID(id uuid.UUID) *CIWorkflowResultUpdate {
	cwru.mutation.SetStorageFileID(id)
	return cwru
}

// SetNillableStorageFileID sets the "storage_file" edge to the StorageFile entity by ID if the given value is not nil.
func (cwru *CIWorkflowResultUpdate) SetNillableStorageFileID(id *uuid.UUID) *CIWorkflowResultUpdate {
	if id != nil {
		cwru = cwru.SetStorageFileID(*id)
	}
	return cwru
}

// SetStorageFile sets the "storage_file" edge to the StorageFile entity.
func (cwru *CIWorkflowResultUpdate) SetStorageFile(s *StorageFile) *CIWorkflowResultUpdate {
	return cwru.SetStorageFileID(s.ID)
}

// Mutation returns the CIWorkflowResultMutation object of the builder.
func (cwru *CIWorkflowResultUpdate) Mutation() *CIWorkflowResultMutation {
	return cwru.mutation
}

// ClearGitcommit clears the "gitcommit" edge to the GitCommit entity.
func (cwru *CIWorkflowResultUpdate) ClearGitcommit() *CIWorkflowResultUpdate {
	cwru.mutation.ClearGitcommit()
	return cwru
}

// ClearStorageFile clears the "storage_file" edge to the StorageFile entity.
func (cwru *CIWorkflowResultUpdate) ClearStorageFile() *CIWorkflowResultUpdate {
	cwru.mutation.ClearStorageFile()
	return cwru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cwru *CIWorkflowResultUpdate) Save(ctx context.Context) (int, error) {
	cwru.defaults()
	return withHooks(ctx, cwru.sqlSave, cwru.mutation, cwru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cwru *CIWorkflowResultUpdate) SaveX(ctx context.Context) int {
	affected, err := cwru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cwru *CIWorkflowResultUpdate) Exec(ctx context.Context) error {
	_, err := cwru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cwru *CIWorkflowResultUpdate) ExecX(ctx context.Context) {
	if err := cwru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cwru *CIWorkflowResultUpdate) defaults() {
	if _, ok := cwru.mutation.UpdateTime(); !ok {
		v := ciworkflowresult.UpdateDefaultUpdateTime()
		cwru.mutation.SetUpdateTime(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (cwru *CIWorkflowResultUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CIWorkflowResultUpdate {
	cwru.modifiers = append(cwru.modifiers, modifiers...)
	return cwru
}

func (cwru *CIWorkflowResultUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(ciworkflowresult.Table, ciworkflowresult.Columns, sqlgraph.NewFieldSpec(ciworkflowresult.FieldID, field.TypeUUID))
	if ps := cwru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cwru.mutation.UpdateTime(); ok {
		_spec.SetField(ciworkflowresult.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := cwru.mutation.OperatingSystem(); ok {
		_spec.SetField(ciworkflowresult.FieldOperatingSystem, field.TypeString, value)
	}
	if value, ok := cwru.mutation.GpuType(); ok {
		_spec.SetField(ciworkflowresult.FieldGpuType, field.TypeString, value)
	}
	if cwru.mutation.GpuTypeCleared() {
		_spec.ClearField(ciworkflowresult.FieldGpuType, field.TypeString)
	}
	if value, ok := cwru.mutation.PytorchVersion(); ok {
		_spec.SetField(ciworkflowresult.FieldPytorchVersion, field.TypeString, value)
	}
	if cwru.mutation.PytorchVersionCleared() {
		_spec.ClearField(ciworkflowresult.FieldPytorchVersion, field.TypeString)
	}
	if value, ok := cwru.mutation.WorkflowName(); ok {
		_spec.SetField(ciworkflowresult.FieldWorkflowName, field.TypeString, value)
	}
	if cwru.mutation.WorkflowNameCleared() {
		_spec.ClearField(ciworkflowresult.FieldWorkflowName, field.TypeString)
	}
	if value, ok := cwru.mutation.RunID(); ok {
		_spec.SetField(ciworkflowresult.FieldRunID, field.TypeString, value)
	}
	if cwru.mutation.RunIDCleared() {
		_spec.ClearField(ciworkflowresult.FieldRunID, field.TypeString)
	}
	if value, ok := cwru.mutation.Status(); ok {
		_spec.SetField(ciworkflowresult.FieldStatus, field.TypeString, value)
	}
	if cwru.mutation.StatusCleared() {
		_spec.ClearField(ciworkflowresult.FieldStatus, field.TypeString)
	}
	if value, ok := cwru.mutation.StartTime(); ok {
		_spec.SetField(ciworkflowresult.FieldStartTime, field.TypeInt64, value)
	}
	if value, ok := cwru.mutation.AddedStartTime(); ok {
		_spec.AddField(ciworkflowresult.FieldStartTime, field.TypeInt64, value)
	}
	if cwru.mutation.StartTimeCleared() {
		_spec.ClearField(ciworkflowresult.FieldStartTime, field.TypeInt64)
	}
	if value, ok := cwru.mutation.EndTime(); ok {
		_spec.SetField(ciworkflowresult.FieldEndTime, field.TypeInt64, value)
	}
	if value, ok := cwru.mutation.AddedEndTime(); ok {
		_spec.AddField(ciworkflowresult.FieldEndTime, field.TypeInt64, value)
	}
	if cwru.mutation.EndTimeCleared() {
		_spec.ClearField(ciworkflowresult.FieldEndTime, field.TypeInt64)
	}
	if cwru.mutation.GitcommitCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ciworkflowresult.GitcommitTable,
			Columns: []string{ciworkflowresult.GitcommitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gitcommit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cwru.mutation.GitcommitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ciworkflowresult.GitcommitTable,
			Columns: []string{ciworkflowresult.GitcommitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gitcommit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cwru.mutation.StorageFileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ciworkflowresult.StorageFileTable,
			Columns: []string{ciworkflowresult.StorageFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagefile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cwru.mutation.StorageFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ciworkflowresult.StorageFileTable,
			Columns: []string{ciworkflowresult.StorageFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagefile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(cwru.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, cwru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ciworkflowresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cwru.mutation.done = true
	return n, nil
}

// CIWorkflowResultUpdateOne is the builder for updating a single CIWorkflowResult entity.
type CIWorkflowResultUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CIWorkflowResultMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (cwruo *CIWorkflowResultUpdateOne) SetUpdateTime(t time.Time) *CIWorkflowResultUpdateOne {
	cwruo.mutation.SetUpdateTime(t)
	return cwruo
}

// SetOperatingSystem sets the "operating_system" field.
func (cwruo *CIWorkflowResultUpdateOne) SetOperatingSystem(s string) *CIWorkflowResultUpdateOne {
	cwruo.mutation.SetOperatingSystem(s)
	return cwruo
}

// SetNillableOperatingSystem sets the "operating_system" field if the given value is not nil.
func (cwruo *CIWorkflowResultUpdateOne) SetNillableOperatingSystem(s *string) *CIWorkflowResultUpdateOne {
	if s != nil {
		cwruo.SetOperatingSystem(*s)
	}
	return cwruo
}

// SetGpuType sets the "gpu_type" field.
func (cwruo *CIWorkflowResultUpdateOne) SetGpuType(s string) *CIWorkflowResultUpdateOne {
	cwruo.mutation.SetGpuType(s)
	return cwruo
}

// SetNillableGpuType sets the "gpu_type" field if the given value is not nil.
func (cwruo *CIWorkflowResultUpdateOne) SetNillableGpuType(s *string) *CIWorkflowResultUpdateOne {
	if s != nil {
		cwruo.SetGpuType(*s)
	}
	return cwruo
}

// ClearGpuType clears the value of the "gpu_type" field.
func (cwruo *CIWorkflowResultUpdateOne) ClearGpuType() *CIWorkflowResultUpdateOne {
	cwruo.mutation.ClearGpuType()
	return cwruo
}

// SetPytorchVersion sets the "pytorch_version" field.
func (cwruo *CIWorkflowResultUpdateOne) SetPytorchVersion(s string) *CIWorkflowResultUpdateOne {
	cwruo.mutation.SetPytorchVersion(s)
	return cwruo
}

// SetNillablePytorchVersion sets the "pytorch_version" field if the given value is not nil.
func (cwruo *CIWorkflowResultUpdateOne) SetNillablePytorchVersion(s *string) *CIWorkflowResultUpdateOne {
	if s != nil {
		cwruo.SetPytorchVersion(*s)
	}
	return cwruo
}

// ClearPytorchVersion clears the value of the "pytorch_version" field.
func (cwruo *CIWorkflowResultUpdateOne) ClearPytorchVersion() *CIWorkflowResultUpdateOne {
	cwruo.mutation.ClearPytorchVersion()
	return cwruo
}

// SetWorkflowName sets the "workflow_name" field.
func (cwruo *CIWorkflowResultUpdateOne) SetWorkflowName(s string) *CIWorkflowResultUpdateOne {
	cwruo.mutation.SetWorkflowName(s)
	return cwruo
}

// SetNillableWorkflowName sets the "workflow_name" field if the given value is not nil.
func (cwruo *CIWorkflowResultUpdateOne) SetNillableWorkflowName(s *string) *CIWorkflowResultUpdateOne {
	if s != nil {
		cwruo.SetWorkflowName(*s)
	}
	return cwruo
}

// ClearWorkflowName clears the value of the "workflow_name" field.
func (cwruo *CIWorkflowResultUpdateOne) ClearWorkflowName() *CIWorkflowResultUpdateOne {
	cwruo.mutation.ClearWorkflowName()
	return cwruo
}

// SetRunID sets the "run_id" field.
func (cwruo *CIWorkflowResultUpdateOne) SetRunID(s string) *CIWorkflowResultUpdateOne {
	cwruo.mutation.SetRunID(s)
	return cwruo
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (cwruo *CIWorkflowResultUpdateOne) SetNillableRunID(s *string) *CIWorkflowResultUpdateOne {
	if s != nil {
		cwruo.SetRunID(*s)
	}
	return cwruo
}

// ClearRunID clears the value of the "run_id" field.
func (cwruo *CIWorkflowResultUpdateOne) ClearRunID() *CIWorkflowResultUpdateOne {
	cwruo.mutation.ClearRunID()
	return cwruo
}

// SetStatus sets the "status" field.
func (cwruo *CIWorkflowResultUpdateOne) SetStatus(s string) *CIWorkflowResultUpdateOne {
	cwruo.mutation.SetStatus(s)
	return cwruo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cwruo *CIWorkflowResultUpdateOne) SetNillableStatus(s *string) *CIWorkflowResultUpdateOne {
	if s != nil {
		cwruo.SetStatus(*s)
	}
	return cwruo
}

// ClearStatus clears the value of the "status" field.
func (cwruo *CIWorkflowResultUpdateOne) ClearStatus() *CIWorkflowResultUpdateOne {
	cwruo.mutation.ClearStatus()
	return cwruo
}

// SetStartTime sets the "start_time" field.
func (cwruo *CIWorkflowResultUpdateOne) SetStartTime(i int64) *CIWorkflowResultUpdateOne {
	cwruo.mutation.ResetStartTime()
	cwruo.mutation.SetStartTime(i)
	return cwruo
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (cwruo *CIWorkflowResultUpdateOne) SetNillableStartTime(i *int64) *CIWorkflowResultUpdateOne {
	if i != nil {
		cwruo.SetStartTime(*i)
	}
	return cwruo
}

// AddStartTime adds i to the "start_time" field.
func (cwruo *CIWorkflowResultUpdateOne) AddStartTime(i int64) *CIWorkflowResultUpdateOne {
	cwruo.mutation.AddStartTime(i)
	return cwruo
}

// ClearStartTime clears the value of the "start_time" field.
func (cwruo *CIWorkflowResultUpdateOne) ClearStartTime() *CIWorkflowResultUpdateOne {
	cwruo.mutation.ClearStartTime()
	return cwruo
}

// SetEndTime sets the "end_time" field.
func (cwruo *CIWorkflowResultUpdateOne) SetEndTime(i int64) *CIWorkflowResultUpdateOne {
	cwruo.mutation.ResetEndTime()
	cwruo.mutation.SetEndTime(i)
	return cwruo
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (cwruo *CIWorkflowResultUpdateOne) SetNillableEndTime(i *int64) *CIWorkflowResultUpdateOne {
	if i != nil {
		cwruo.SetEndTime(*i)
	}
	return cwruo
}

// AddEndTime adds i to the "end_time" field.
func (cwruo *CIWorkflowResultUpdateOne) AddEndTime(i int64) *CIWorkflowResultUpdateOne {
	cwruo.mutation.AddEndTime(i)
	return cwruo
}

// ClearEndTime clears the value of the "end_time" field.
func (cwruo *CIWorkflowResultUpdateOne) ClearEndTime() *CIWorkflowResultUpdateOne {
	cwruo.mutation.ClearEndTime()
	return cwruo
}

// SetGitcommitID sets the "gitcommit" edge to the GitCommit entity by ID.
func (cwruo *CIWorkflowResultUpdateOne) SetGitcommitID(id uuid.UUID) *CIWorkflowResultUpdateOne {
	cwruo.mutation.SetGitcommitID(id)
	return cwruo
}

// SetNillableGitcommitID sets the "gitcommit" edge to the GitCommit entity by ID if the given value is not nil.
func (cwruo *CIWorkflowResultUpdateOne) SetNillableGitcommitID(id *uuid.UUID) *CIWorkflowResultUpdateOne {
	if id != nil {
		cwruo = cwruo.SetGitcommitID(*id)
	}
	return cwruo
}

// SetGitcommit sets the "gitcommit" edge to the GitCommit entity.
func (cwruo *CIWorkflowResultUpdateOne) SetGitcommit(g *GitCommit) *CIWorkflowResultUpdateOne {
	return cwruo.SetGitcommitID(g.ID)
}

// SetStorageFileID sets the "storage_file" edge to the StorageFile entity by ID.
func (cwruo *CIWorkflowResultUpdateOne) SetStorageFileID(id uuid.UUID) *CIWorkflowResultUpdateOne {
	cwruo.mutation.SetStorageFileID(id)
	return cwruo
}

// SetNillableStorageFileID sets the "storage_file" edge to the StorageFile entity by ID if the given value is not nil.
func (cwruo *CIWorkflowResultUpdateOne) SetNillableStorageFileID(id *uuid.UUID) *CIWorkflowResultUpdateOne {
	if id != nil {
		cwruo = cwruo.SetStorageFileID(*id)
	}
	return cwruo
}

// SetStorageFile sets the "storage_file" edge to the StorageFile entity.
func (cwruo *CIWorkflowResultUpdateOne) SetStorageFile(s *StorageFile) *CIWorkflowResultUpdateOne {
	return cwruo.SetStorageFileID(s.ID)
}

// Mutation returns the CIWorkflowResultMutation object of the builder.
func (cwruo *CIWorkflowResultUpdateOne) Mutation() *CIWorkflowResultMutation {
	return cwruo.mutation
}

// ClearGitcommit clears the "gitcommit" edge to the GitCommit entity.
func (cwruo *CIWorkflowResultUpdateOne) ClearGitcommit() *CIWorkflowResultUpdateOne {
	cwruo.mutation.ClearGitcommit()
	return cwruo
}

// ClearStorageFile clears the "storage_file" edge to the StorageFile entity.
func (cwruo *CIWorkflowResultUpdateOne) ClearStorageFile() *CIWorkflowResultUpdateOne {
	cwruo.mutation.ClearStorageFile()
	return cwruo
}

// Where appends a list predicates to the CIWorkflowResultUpdate builder.
func (cwruo *CIWorkflowResultUpdateOne) Where(ps ...predicate.CIWorkflowResult) *CIWorkflowResultUpdateOne {
	cwruo.mutation.Where(ps...)
	return cwruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cwruo *CIWorkflowResultUpdateOne) Select(field string, fields ...string) *CIWorkflowResultUpdateOne {
	cwruo.fields = append([]string{field}, fields...)
	return cwruo
}

// Save executes the query and returns the updated CIWorkflowResult entity.
func (cwruo *CIWorkflowResultUpdateOne) Save(ctx context.Context) (*CIWorkflowResult, error) {
	cwruo.defaults()
	return withHooks(ctx, cwruo.sqlSave, cwruo.mutation, cwruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cwruo *CIWorkflowResultUpdateOne) SaveX(ctx context.Context) *CIWorkflowResult {
	node, err := cwruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cwruo *CIWorkflowResultUpdateOne) Exec(ctx context.Context) error {
	_, err := cwruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cwruo *CIWorkflowResultUpdateOne) ExecX(ctx context.Context) {
	if err := cwruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cwruo *CIWorkflowResultUpdateOne) defaults() {
	if _, ok := cwruo.mutation.UpdateTime(); !ok {
		v := ciworkflowresult.UpdateDefaultUpdateTime()
		cwruo.mutation.SetUpdateTime(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (cwruo *CIWorkflowResultUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CIWorkflowResultUpdateOne {
	cwruo.modifiers = append(cwruo.modifiers, modifiers...)
	return cwruo
}

func (cwruo *CIWorkflowResultUpdateOne) sqlSave(ctx context.Context) (_node *CIWorkflowResult, err error) {
	_spec := sqlgraph.NewUpdateSpec(ciworkflowresult.Table, ciworkflowresult.Columns, sqlgraph.NewFieldSpec(ciworkflowresult.FieldID, field.TypeUUID))
	id, ok := cwruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CIWorkflowResult.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cwruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ciworkflowresult.FieldID)
		for _, f := range fields {
			if !ciworkflowresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ciworkflowresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cwruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cwruo.mutation.UpdateTime(); ok {
		_spec.SetField(ciworkflowresult.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := cwruo.mutation.OperatingSystem(); ok {
		_spec.SetField(ciworkflowresult.FieldOperatingSystem, field.TypeString, value)
	}
	if value, ok := cwruo.mutation.GpuType(); ok {
		_spec.SetField(ciworkflowresult.FieldGpuType, field.TypeString, value)
	}
	if cwruo.mutation.GpuTypeCleared() {
		_spec.ClearField(ciworkflowresult.FieldGpuType, field.TypeString)
	}
	if value, ok := cwruo.mutation.PytorchVersion(); ok {
		_spec.SetField(ciworkflowresult.FieldPytorchVersion, field.TypeString, value)
	}
	if cwruo.mutation.PytorchVersionCleared() {
		_spec.ClearField(ciworkflowresult.FieldPytorchVersion, field.TypeString)
	}
	if value, ok := cwruo.mutation.WorkflowName(); ok {
		_spec.SetField(ciworkflowresult.FieldWorkflowName, field.TypeString, value)
	}
	if cwruo.mutation.WorkflowNameCleared() {
		_spec.ClearField(ciworkflowresult.FieldWorkflowName, field.TypeString)
	}
	if value, ok := cwruo.mutation.RunID(); ok {
		_spec.SetField(ciworkflowresult.FieldRunID, field.TypeString, value)
	}
	if cwruo.mutation.RunIDCleared() {
		_spec.ClearField(ciworkflowresult.FieldRunID, field.TypeString)
	}
	if value, ok := cwruo.mutation.Status(); ok {
		_spec.SetField(ciworkflowresult.FieldStatus, field.TypeString, value)
	}
	if cwruo.mutation.StatusCleared() {
		_spec.ClearField(ciworkflowresult.FieldStatus, field.TypeString)
	}
	if value, ok := cwruo.mutation.StartTime(); ok {
		_spec.SetField(ciworkflowresult.FieldStartTime, field.TypeInt64, value)
	}
	if value, ok := cwruo.mutation.AddedStartTime(); ok {
		_spec.AddField(ciworkflowresult.FieldStartTime, field.TypeInt64, value)
	}
	if cwruo.mutation.StartTimeCleared() {
		_spec.ClearField(ciworkflowresult.FieldStartTime, field.TypeInt64)
	}
	if value, ok := cwruo.mutation.EndTime(); ok {
		_spec.SetField(ciworkflowresult.FieldEndTime, field.TypeInt64, value)
	}
	if value, ok := cwruo.mutation.AddedEndTime(); ok {
		_spec.AddField(ciworkflowresult.FieldEndTime, field.TypeInt64, value)
	}
	if cwruo.mutation.EndTimeCleared() {
		_spec.ClearField(ciworkflowresult.FieldEndTime, field.TypeInt64)
	}
	if cwruo.mutation.GitcommitCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ciworkflowresult.GitcommitTable,
			Columns: []string{ciworkflowresult.GitcommitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gitcommit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cwruo.mutation.GitcommitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ciworkflowresult.GitcommitTable,
			Columns: []string{ciworkflowresult.GitcommitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gitcommit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cwruo.mutation.StorageFileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ciworkflowresult.StorageFileTable,
			Columns: []string{ciworkflowresult.StorageFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagefile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cwruo.mutation.StorageFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ciworkflowresult.StorageFileTable,
			Columns: []string{ciworkflowresult.StorageFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagefile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(cwruo.modifiers...)
	_node = &CIWorkflowResult{config: cwruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cwruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ciworkflowresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cwruo.mutation.done = true
	return _node, nil
}
