// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"registry-backend/ent/feedbackmessage"
	"registry-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FeedbackMessageDelete is the builder for deleting a FeedbackMessage entity.
type FeedbackMessageDelete struct {
	config
	hooks    []Hook
	mutation *FeedbackMessageMutation
}

// Where appends a list predicates to the FeedbackMessageDelete builder.
func (fmd *FeedbackMessageDelete) Where(ps ...predicate.FeedbackMessage) *FeedbackMessageDelete {
	fmd.mutation.Where(ps...)
	return fmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fmd *FeedbackMessageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fmd.sqlExec, fmd.mutation, fmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fmd *FeedbackMessageDelete) ExecX(ctx context.Context) int {
	n, err := fmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fmd *FeedbackMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(feedbackmessage.Table, sqlgraph.NewFieldSpec(feedbackmessage.FieldID, field.TypeUUID))
	if ps := fmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fmd.mutation.done = true
	return affected, err
}

// FeedbackMessageDeleteOne is the builder for deleting a single FeedbackMessage entity.
type FeedbackMessageDeleteOne struct {
	fmd *FeedbackMessageDelete
}

// Where appends a list predicates to the FeedbackMessageDelete builder.
func (fmdo *FeedbackMessageDeleteOne) Where(ps ...predicate.FeedbackMessage) *FeedbackMessageDeleteOne {
	fmdo.fmd.mutation.Where(ps...)
	return fmdo
}

// Exec executes the deletion query.
func (fmdo *FeedbackMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := fmdo.fmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{feedbackmessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fmdo *FeedbackMessageDeleteOne) ExecX(ctx context.Context) {
	if err := fmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
