// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"registry-backend/ent/feedbackthread"
	"registry-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FeedbackThreadDelete is the builder for deleting a FeedbackThread entity.
type FeedbackThreadDelete struct {
	config
	hooks    []Hook
	mutation *FeedbackThreadMutation
}

// Where appends a list predicates to the FeedbackThreadDelete builder.
func (ftd *FeedbackThreadDelete) Where(ps ...predicate.FeedbackThread) *FeedbackThreadDelete {
	ftd.mutation.Where(ps...)
	return ftd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ftd *FeedbackThreadDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ftd.sqlExec, ftd.mutation, ftd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ftd *FeedbackThreadDelete) ExecX(ctx context.Context) int {
	n, err := ftd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ftd *FeedbackThreadDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(feedbackthread.Table, sqlgraph.NewFieldSpec(feedbackthread.FieldID, field.TypeUUID))
	if ps := ftd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ftd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ftd.mutation.done = true
	return affected, err
}

// FeedbackThreadDeleteOne is the builder for deleting a single FeedbackThread entity.
type FeedbackThreadDeleteOne struct {
	ftd *FeedbackThreadDelete
}

// Where appends a list predicates to the FeedbackThreadDelete builder.
func (ftdo *FeedbackThreadDeleteOne) Where(ps ...predicate.FeedbackThread) *FeedbackThreadDeleteOne {
	ftdo.ftd.mutation.Where(ps...)
	return ftdo
}

// Exec executes the deletion query.
func (ftdo *FeedbackThreadDeleteOne) Exec(ctx context.Context) error {
	n, err := ftdo.ftd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{feedbackthread.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ftdo *FeedbackThreadDeleteOne) ExecX(ctx context.Context) {
	if err := ftdo.Exec(ctx); err != nil {
		panic(err)
	}
}
