// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"registry-backend/ent/feedbackevent"
	"registry-backend/ent/feedbackthread"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// FeedbackEvent is the model entity for the FeedbackEvent schema.
type FeedbackEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ThreadID holds the value of the "thread_id" field.
	ThreadID uuid.UUID `json:"thread_id,omitempty"`
	// ActorUserID holds the value of the "actor_user_id" field.
	ActorUserID string `json:"actor_user_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType feedbackevent.EventType `json:"event_type,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ReplacementVersionID holds the value of the "replacement_version_id" field.
	ReplacementVersionID *uuid.UUID `json:"replacement_version_id,omitempty"`
	// ReplacementVersion holds the value of the "replacement_version" field.
	ReplacementVersion *string `json:"replacement_version,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FeedbackEventQuery when eager-loading is set.
	Edges        FeedbackEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FeedbackEventEdges holds the relations/edges for other nodes in the graph.
type FeedbackEventEdges struct {
	// Thread holds the value of the thread edge.
	Thread *FeedbackThread `json:"thread,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ThreadOrErr returns the Thread value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FeedbackEventEdges) ThreadOrErr() (*FeedbackThread, error) {
	if e.Thread != nil {
		return e.Thread, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: feedbackthread.Label}
	}
	return nil, &NotLoadedError{edge: "thread"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FeedbackEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case feedbackevent.FieldReplacementVersionID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case feedbackevent.FieldActorUserID, feedbackevent.FieldEventType, feedbackevent.FieldReplacementVersion:
			values[i] = new(sql.NullString)
		case feedbackevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case feedbackevent.FieldID, feedbackevent.FieldThreadID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FeedbackEvent fields.
func (fe *FeedbackEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case feedbackevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				fe.ID = *value
			}
		case feedbackevent.FieldThreadID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field thread_id", values[i])
			} else if value != nil {
				fe.ThreadID = *value
			}
		case feedbackevent.FieldActorUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_user_id", values[i])
			} else if value.Valid {
				fe.ActorUserID = value.String
			}
		case feedbackevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				fe.EventType = feedbackevent.EventType(value.String)
			}
		case feedbackevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				fe.CreatedAt = value.Time
			}
		case feedbackevent.FieldReplacementVersionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field replacement_version_id", values[i])
			} else if value.Valid {
				fe.ReplacementVersionID = new(uuid.UUID)
				*fe.ReplacementVersionID = *value.S.(*uuid.UUID)
			}
		case feedbackevent.FieldReplacementVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field replacement_version", values[i])
			} else if value.Valid {
				fe.ReplacementVersion = new(string)
				*fe.ReplacementVersion = value.String
			}
		default:
			fe.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FeedbackEvent.
// This includes values selected through modifiers, order, etc.
func (fe *FeedbackEvent) Value(name string) (ent.Value, error) {
	return fe.selectValues.Get(name)
}

// QueryThread queries the "thread" edge of the FeedbackEvent entity.
func (fe *FeedbackEvent) QueryThread() *FeedbackThreadQuery {
	return NewFeedbackEventClient(fe.config).QueryThread(fe)
}

// Update returns a builder for updating this FeedbackEvent.
// Note that you need to call FeedbackEvent.Unwrap() before calling this method if this FeedbackEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (fe *FeedbackEvent) Update() *FeedbackEventUpdateOne {
	return NewFeedbackEventClient(fe.config).UpdateOne(fe)
}

// Unwrap unwraps the FeedbackEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (fe *FeedbackEvent) Unwrap() *FeedbackEvent {
	_tx, ok := fe.config.driver.(*txDriver)
	if !ok {
		panic("ent: FeedbackEvent is not a transactional entity")
	}
	fe.config.driver = _tx.drv
	return fe
}

// String implements the fmt.Stringer.
func (fe *FeedbackEvent) String() string {
	var builder strings.Builder
	builder.WriteString("FeedbackEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", fe.ID))
	builder.WriteString("thread_id=")
	builder.WriteString(fmt.Sprintf("%v", fe.ThreadID))
	builder.WriteString(", ")
	builder.WriteString("actor_user_id=")
	builder.WriteString(fe.ActorUserID)
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(fmt.Sprintf("%v", fe.EventType))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fe.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := fe.ReplacementVersionID; v != nil {
		builder.WriteString("replacement_version_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := fe.ReplacementVersion; v != nil {
		builder.WriteString("replacement_version=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// FeedbackEvents is a parsable slice of FeedbackEvent.
type FeedbackEvents []*FeedbackEvent
