// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"registry-backend/ent/feedbackread"
	"registry-backend/ent/feedbackthread"
	"registry-backend/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FeedbackReadQuery is the builder for querying FeedbackRead entities.
type FeedbackReadQuery struct {
	config
	ctx        *QueryContext
	order      []feedbackread.OrderOption
	inters     []Interceptor
	predicates []predicate.FeedbackRead
	withThread *FeedbackThreadQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FeedbackReadQuery builder.
func (frq *FeedbackReadQuery) Where(ps ...predicate.FeedbackRead) *FeedbackReadQuery {
	frq.predicates = append(frq.predicates, ps...)
	return frq
}

// Limit the number of records to be returned by this query.
func (frq *FeedbackReadQuery) Limit(limit int) *FeedbackReadQuery {
	frq.ctx.Limit = &limit
	return frq
}

// Offset to start from.
func (frq *FeedbackReadQuery) Offset(offset int) *FeedbackReadQuery {
	frq.ctx.Offset = &offset
	return frq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (frq *FeedbackReadQuery) Unique(unique bool) *FeedbackReadQuery {
	frq.ctx.Unique = &unique
	return frq
}

// Order specifies how the records should be ordered.
func (frq *FeedbackReadQuery) Order(o ...feedbackread.OrderOption) *FeedbackReadQuery {
	frq.order = append(frq.order, o...)
	return frq
}

// QueryThread chains the current query on the "thread" edge.
func (frq *FeedbackReadQuery) QueryThread() *FeedbackThreadQuery {
	query := (&FeedbackThreadClient{config: frq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := frq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := frq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(feedbackread.Table, feedbackread.FieldID, selector),
			sqlgraph.To(feedbackthread.Table, feedbackthread.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, feedbackread.ThreadTable, feedbackread.ThreadColumn),
		)
		fromU = sqlgraph.SetNeighbors(frq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FeedbackRead entity from the query.
// Returns a *NotFoundError when no FeedbackRead was found.
func (frq *FeedbackReadQuery) First(ctx context.Context) (*FeedbackRead, error) {
	nodes, err := frq.Limit(1).All(setContextOp(ctx, frq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{feedbackread.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (frq *FeedbackReadQuery) FirstX(ctx context.Context) *FeedbackRead {
	node, err := frq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FeedbackRead ID from the query.
// Returns a *NotFoundError when no FeedbackRead ID was found.
func (frq *FeedbackReadQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = frq.Limit(1).IDs(setContextOp(ctx, frq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{feedbackread.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (frq *FeedbackReadQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := frq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FeedbackRead entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FeedbackRead entity is found.
// Returns a *NotFoundError when no FeedbackRead entities are found.
func (frq *FeedbackReadQuery) Only(ctx context.Context) (*FeedbackRead, error) {
	nodes, err := frq.Limit(2).All(setContextOp(ctx, frq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{feedbackread.Label}
	default:
		return nil, &NotSingularError{feedbackread.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (frq *FeedbackReadQuery) OnlyX(ctx context.Context) *FeedbackRead {
	node, err := frq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FeedbackRead ID in the query.
// Returns a *NotSingularError when more than one FeedbackRead ID is found.
// Returns a *NotFoundError when no entities are found.
func (frq *FeedbackReadQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = frq.Limit(2).IDs(setContextOp(ctx, frq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{feedbackread.Label}
	default:
		err = &NotSingularError{feedbackread.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (frq *FeedbackReadQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := frq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FeedbackReads.
func (frq *FeedbackReadQuery) All(ctx context.Context) ([]*FeedbackRead, error) {
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryAll)
	if err := frq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FeedbackRead, *FeedbackReadQuery]()
	return withInterceptors[[]*FeedbackRead](ctx, frq, qr, frq.inters)
}

// AllX is like All, but panics if an error occurs.
func (frq *FeedbackReadQuery) AllX(ctx context.Context) []*FeedbackRead {
	nodes, err := frq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FeedbackRead IDs.
func (frq *FeedbackReadQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if frq.ctx.Unique == nil && frq.path != nil {
		frq.Unique(true)
	}
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryIDs)
	if err = frq.Select(feedbackread.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (frq *FeedbackReadQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := frq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (frq *FeedbackReadQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryCount)
	if err := frq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, frq, querierCount[*FeedbackReadQuery](), frq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (frq *FeedbackReadQuery) CountX(ctx context.Context) int {
	count, err := frq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (frq *FeedbackReadQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryExist)
	switch _, err := frq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (frq *FeedbackReadQuery) ExistX(ctx context.Context) bool {
	exist, err := frq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FeedbackReadQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (frq *FeedbackReadQuery) Clone() *FeedbackReadQuery {
	if frq == nil {
		return nil
	}
	return &FeedbackReadQuery{
		config:     frq.config,
		ctx:        frq.ctx.Clone(),
		order:      append([]feedbackread.OrderOption{}, frq.order...),
		inters:     append([]Interceptor{}, frq.inters...),
		predicates: append([]predicate.FeedbackRead{}, frq.predicates...),
		withThread: frq.withThread.Clone(),
		// clone intermediate query.
		sql:       frq.sql.Clone(),
		path:      frq.path,
		modifiers: append([]func(*sql.Selector){}, frq.modifiers...),
	}
}

// WithThread tells the query-builder to eager-load the nodes that are connected to
// the "thread" edge. The optional arguments are used to configure the query builder of the edge.
func (frq *FeedbackReadQuery) WithThread(opts ...func(*FeedbackThreadQuery)) *FeedbackReadQuery {
	query := (&FeedbackThreadClient{config: frq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	frq.withThread = query
	return frq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ThreadID uuid.UUID `json:"thread_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FeedbackRead.Query().
//		GroupBy(feedbackread.FieldThreadID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (frq *FeedbackReadQuery) GroupBy(field string, fields ...string) *FeedbackReadGroupBy {
	frq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FeedbackReadGroupBy{build: frq}
	grbuild.flds = &frq.ctx.Fields
	grbuild.label = feedbackread.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ThreadID uuid.UUID `json:"thread_id,omitempty"`
//	}
//
//	client.FeedbackRead.Query().
//		Select(feedbackread.FieldThreadID).
//		Scan(ctx, &v)
func (frq *FeedbackReadQuery) Select(fields ...string) *FeedbackReadSelect {
	frq.ctx.Fields = append(frq.ctx.Fields, fields...)
	sbuild := &FeedbackReadSelect{FeedbackReadQuery: frq}
	sbuild.label = feedbackread.Label
	sbuild.flds, sbuild.scan = &frq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FeedbackReadSelect configured with the given aggregations.
func (frq *FeedbackReadQuery) Aggregate(fns ...AggregateFunc) *FeedbackReadSelect {
	return frq.Select().Aggregate(fns...)
}

func (frq *FeedbackReadQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range frq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, frq); err != nil {
				return err
			}
		}
	}
	for _, f := range frq.ctx.Fields {
		if !feedbackread.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if frq.path != nil {
		prev, err := frq.path(ctx)
		if err != nil {
			return err
		}
		frq.sql = prev
	}
	return nil
}

func (frq *FeedbackReadQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FeedbackRead, error) {
	var (
		nodes       = []*FeedbackRead{}
		_spec       = frq.querySpec()
		loadedTypes = [1]bool{
			frq.withThread != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FeedbackRead).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FeedbackRead{config: frq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(frq.modifiers) > 0 {
		_spec.Modifiers = frq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, frq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := frq.withThread; query != nil {
		if err := frq.loadThread(ctx, query, nodes, nil,
			func(n *FeedbackRead, e *FeedbackThread) { n.Edges.Thread = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (frq *FeedbackReadQuery) loadThread(ctx context.Context, query *FeedbackThreadQuery, nodes []*FeedbackRead, init func(*FeedbackRead), assign func(*FeedbackRead, *FeedbackThread)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*FeedbackRead)
	for i := range nodes {
		fk := nodes[i].ThreadID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(feedbackthread.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "thread_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (frq *FeedbackReadQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := frq.querySpec()
	if len(frq.modifiers) > 0 {
		_spec.Modifiers = frq.modifiers
	}
	_spec.Node.Columns = frq.ctx.Fields
	if len(frq.ctx.Fields) > 0 {
		_spec.Unique = frq.ctx.Unique != nil && *frq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, frq.driver, _spec)
}

func (frq *FeedbackReadQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(feedbackread.Table, feedbackread.Columns, sqlgraph.NewFieldSpec(feedbackread.FieldID, field.TypeUUID))
	_spec.From = frq.sql
	if unique := frq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if frq.path != nil {
		_spec.Unique = true
	}
	if fields := frq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, feedbackread.FieldID)
		for i := range fields {
			if fields[i] != feedbackread.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if frq.withThread != nil {
			_spec.Node.AddColumnOnce(feedbackread.FieldThreadID)
		}
	}
	if ps := frq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := frq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := frq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := frq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (frq *FeedbackReadQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(frq.driver.Dialect())
	t1 := builder.Table(feedbackread.Table)
	columns := frq.ctx.Fields
	if len(columns) == 0 {
		columns = feedbackread.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if frq.sql != nil {
		selector = frq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if frq.ctx.Unique != nil && *frq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range frq.modifiers {
		m(selector)
	}
	for _, p := range frq.predicates {
		p(selector)
	}
	for _, p := range frq.order {
		p(selector)
	}
	if offset := frq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := frq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (frq *FeedbackReadQuery) ForUpdate(opts ...sql.LockOption) *FeedbackReadQuery {
	if frq.driver.Dialect() == dialect.Postgres {
		frq.Unique(false)
	}
	frq.modifiers = append(frq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return frq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (frq *FeedbackReadQuery) ForShare(opts ...sql.LockOption) *FeedbackReadQuery {
	if frq.driver.Dialect() == dialect.Postgres {
		frq.Unique(false)
	}
	frq.modifiers = append(frq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return frq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (frq *FeedbackReadQuery) Modify(modifiers ...func(s *sql.Selector)) *FeedbackReadSelect {
	frq.modifiers = append(frq.modifiers, modifiers...)
	return frq.Select()
}

// FeedbackReadGroupBy is the group-by builder for FeedbackRead entities.
type FeedbackReadGroupBy struct {
	selector
	build *FeedbackReadQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (frgb *FeedbackReadGroupBy) Aggregate(fns ...AggregateFunc) *FeedbackReadGroupBy {
	frgb.fns = append(frgb.fns, fns...)
	return frgb
}

// Scan applies the selector query and scans the result into the given value.
func (frgb *FeedbackReadGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, frgb.build.ctx, ent.OpQueryGroupBy)
	if err := frgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FeedbackReadQuery, *FeedbackReadGroupBy](ctx, frgb.build, frgb, frgb.build.inters, v)
}

func (frgb *FeedbackReadGroupBy) sqlScan(ctx context.Context, root *FeedbackReadQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(frgb.fns))
	for _, fn := range frgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*frgb.flds)+len(frgb.fns))
		for _, f := range *frgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*frgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := frgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FeedbackReadSelect is the builder for selecting fields of FeedbackRead entities.
type FeedbackReadSelect struct {
	*FeedbackReadQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (frs *FeedbackReadSelect) Aggregate(fns ...AggregateFunc) *FeedbackReadSelect {
	frs.fns = append(frs.fns, fns...)
	return frs
}

// Scan applies the selector query and scans the result into the given value.
func (frs *FeedbackReadSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, frs.ctx, ent.OpQuerySelect)
	if err := frs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FeedbackReadQuery, *FeedbackReadSelect](ctx, frs.FeedbackReadQuery, frs, frs.inters, v)
}

func (frs *FeedbackReadSelect) sqlScan(ctx context.Context, root *FeedbackReadQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(frs.fns))
	for _, fn := range frs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*frs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := frs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (frs *FeedbackReadSelect) Modify(modifiers ...func(s *sql.Selector)) *FeedbackReadSelect {
	frs.modifiers = append(frs.modifiers, modifiers...)
	return frs
}
