// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"registry-backend/ent/feedbackmessage"
	"registry-backend/ent/feedbackthread"
	"registry-backend/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FeedbackMessageQuery is the builder for querying FeedbackMessage entities.
type FeedbackMessageQuery struct {
	config
	ctx        *QueryContext
	order      []feedbackmessage.OrderOption
	inters     []Interceptor
	predicates []predicate.FeedbackMessage
	withThread *FeedbackThreadQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FeedbackMessageQuery builder.
func (fmq *FeedbackMessageQuery) Where(ps ...predicate.FeedbackMessage) *FeedbackMessageQuery {
	fmq.predicates = append(fmq.predicates, ps...)
	return fmq
}

// Limit the number of records to be returned by this query.
func (fmq *FeedbackMessageQuery) Limit(limit int) *FeedbackMessageQuery {
	fmq.ctx.Limit = &limit
	return fmq
}

// Offset to start from.
func (fmq *FeedbackMessageQuery) Offset(offset int) *FeedbackMessageQuery {
	fmq.ctx.Offset = &offset
	return fmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fmq *FeedbackMessageQuery) Unique(unique bool) *FeedbackMessageQuery {
	fmq.ctx.Unique = &unique
	return fmq
}

// Order specifies how the records should be ordered.
func (fmq *FeedbackMessageQuery) Order(o ...feedbackmessage.OrderOption) *FeedbackMessageQuery {
	fmq.order = append(fmq.order, o...)
	return fmq
}

// QueryThread chains the current query on the "thread" edge.
func (fmq *FeedbackMessageQuery) QueryThread() *FeedbackThreadQuery {
	query := (&FeedbackThreadClient{config: fmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(feedbackmessage.Table, feedbackmessage.FieldID, selector),
			sqlgraph.To(feedbackthread.Table, feedbackthread.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, feedbackmessage.ThreadTable, feedbackmessage.ThreadColumn),
		)
		fromU = sqlgraph.SetNeighbors(fmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FeedbackMessage entity from the query.
// Returns a *NotFoundError when no FeedbackMessage was found.
func (fmq *FeedbackMessageQuery) First(ctx context.Context) (*FeedbackMessage, error) {
	nodes, err := fmq.Limit(1).All(setContextOp(ctx, fmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{feedbackmessage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fmq *FeedbackMessageQuery) FirstX(ctx context.Context) *FeedbackMessage {
	node, err := fmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FeedbackMessage ID from the query.
// Returns a *NotFoundError when no FeedbackMessage ID was found.
func (fmq *FeedbackMessageQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = fmq.Limit(1).IDs(setContextOp(ctx, fmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{feedbackmessage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fmq *FeedbackMessageQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := fmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FeedbackMessage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FeedbackMessage entity is found.
// Returns a *NotFoundError when no FeedbackMessage entities are found.
func (fmq *FeedbackMessageQuery) Only(ctx context.Context) (*FeedbackMessage, error) {
	nodes, err := fmq.Limit(2).All(setContextOp(ctx, fmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{feedbackmessage.Label}
	default:
		return nil, &NotSingularError{feedbackmessage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fmq *FeedbackMessageQuery) OnlyX(ctx context.Context) *FeedbackMessage {
	node, err := fmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FeedbackMessage ID in the query.
// Returns a *NotSingularError when more than one FeedbackMessage ID is found.
// Returns a *NotFoundError when no entities are found.
func (fmq *FeedbackMessageQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = fmq.Limit(2).IDs(setContextOp(ctx, fmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{feedbackmessage.Label}
	default:
		err = &NotSingularError{feedbackmessage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fmq *FeedbackMessageQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := fmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FeedbackMessages.
func (fmq *FeedbackMessageQuery) All(ctx context.Context) ([]*FeedbackMessage, error) {
	ctx = setContextOp(ctx, fmq.ctx, ent.OpQueryAll)
	if err := fmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FeedbackMessage, *FeedbackMessageQuery]()
	return withInterceptors[[]*FeedbackMessage](ctx, fmq, qr, fmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fmq *FeedbackMessageQuery) AllX(ctx context.Context) []*FeedbackMessage {
	nodes, err := fmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FeedbackMessage IDs.
func (fmq *FeedbackMessageQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if fmq.ctx.Unique == nil && fmq.path != nil {
		fmq.Unique(true)
	}
	ctx = setContextOp(ctx, fmq.ctx, ent.OpQueryIDs)
	if err = fmq.Select(feedbackmessage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fmq *FeedbackMessageQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := fmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fmq *FeedbackMessageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fmq.ctx, ent.OpQueryCount)
	if err := fmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fmq, querierCount[*FeedbackMessageQuery](), fmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fmq *FeedbackMessageQuery) CountX(ctx context.Context) int {
	count, err := fmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fmq *FeedbackMessageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fmq.ctx, ent.OpQueryExist)
	switch _, err := fmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fmq *FeedbackMessageQuery) ExistX(ctx context.Context) bool {
	exist, err := fmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FeedbackMessageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fmq *FeedbackMessageQuery) Clone() *FeedbackMessageQuery {
	if fmq == nil {
		return nil
	}
	return &FeedbackMessageQuery{
		config:     fmq.config,
		ctx:        fmq.ctx.Clone(),
		order:      append([]feedbackmessage.OrderOption{}, fmq.order...),
		inters:     append([]Interceptor{}, fmq.inters...),
		predicates: append([]predicate.FeedbackMessage{}, fmq.predicates...),
		withThread: fmq.withThread.Clone(),
		// clone intermediate query.
		sql:       fmq.sql.Clone(),
		path:      fmq.path,
		modifiers: append([]func(*sql.Selector){}, fmq.modifiers...),
	}
}

// WithThread tells the query-builder to eager-load the nodes that are connected to
// the "thread" edge. The optional arguments are used to configure the query builder of the edge.
func (fmq *FeedbackMessageQuery) WithThread(opts ...func(*FeedbackThreadQuery)) *FeedbackMessageQuery {
	query := (&FeedbackThreadClient{config: fmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fmq.withThread = query
	return fmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ThreadID uuid.UUID `json:"thread_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FeedbackMessage.Query().
//		GroupBy(feedbackmessage.FieldThreadID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fmq *FeedbackMessageQuery) GroupBy(field string, fields ...string) *FeedbackMessageGroupBy {
	fmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FeedbackMessageGroupBy{build: fmq}
	grbuild.flds = &fmq.ctx.Fields
	grbuild.label = feedbackmessage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ThreadID uuid.UUID `json:"thread_id,omitempty"`
//	}
//
//	client.FeedbackMessage.Query().
//		Select(feedbackmessage.FieldThreadID).
//		Scan(ctx, &v)
func (fmq *FeedbackMessageQuery) Select(fields ...string) *FeedbackMessageSelect {
	fmq.ctx.Fields = append(fmq.ctx.Fields, fields...)
	sbuild := &FeedbackMessageSelect{FeedbackMessageQuery: fmq}
	sbuild.label = feedbackmessage.Label
	sbuild.flds, sbuild.scan = &fmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FeedbackMessageSelect configured with the given aggregations.
func (fmq *FeedbackMessageQuery) Aggregate(fns ...AggregateFunc) *FeedbackMessageSelect {
	return fmq.Select().Aggregate(fns...)
}

func (fmq *FeedbackMessageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fmq); err != nil {
				return err
			}
		}
	}
	for _, f := range fmq.ctx.Fields {
		if !feedbackmessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fmq.path != nil {
		prev, err := fmq.path(ctx)
		if err != nil {
			return err
		}
		fmq.sql = prev
	}
	return nil
}

func (fmq *FeedbackMessageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FeedbackMessage, error) {
	var (
		nodes       = []*FeedbackMessage{}
		_spec       = fmq.querySpec()
		loadedTypes = [1]bool{
			fmq.withThread != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FeedbackMessage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FeedbackMessage{config: fmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(fmq.modifiers) > 0 {
		_spec.Modifiers = fmq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fmq.withThread; query != nil {
		if err := fmq.loadThread(ctx, query, nodes, nil,
			func(n *FeedbackMessage, e *FeedbackThread) { n.Edges.Thread = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fmq *FeedbackMessageQuery) loadThread(ctx context.Context, query *FeedbackThreadQuery, nodes []*FeedbackMessage, init func(*FeedbackMessage), assign func(*FeedbackMessage, *FeedbackThread)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*FeedbackMessage)
	for i := range nodes {
		fk := nodes[i].ThreadID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(feedbackthread.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "thread_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (fmq *FeedbackMessageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fmq.querySpec()
	if len(fmq.modifiers) > 0 {
		_spec.Modifiers = fmq.modifiers
	}
	_spec.Node.Columns = fmq.ctx.Fields
	if len(fmq.ctx.Fields) > 0 {
		_spec.Unique = fmq.ctx.Unique != nil && *fmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fmq.driver, _spec)
}

func (fmq *FeedbackMessageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(feedbackmessage.Table, feedbackmessage.Columns, sqlgraph.NewFieldSpec(feedbackmessage.FieldID, field.TypeUUID))
	_spec.From = fmq.sql
	if unique := fmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fmq.path != nil {
		_spec.Unique = true
	}
	if fields := fmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, feedbackmessage.FieldID)
		for i := range fields {
			if fields[i] != feedbackmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if fmq.withThread != nil {
			_spec.Node.AddColumnOnce(feedbackmessage.FieldThreadID)
		}
	}
	if ps := fmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fmq *FeedbackMessageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fmq.driver.Dialect())
	t1 := builder.Table(feedbackmessage.Table)
	columns := fmq.ctx.Fields
	if len(columns) == 0 {
		columns = feedbackmessage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fmq.sql != nil {
		selector = fmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fmq.ctx.Unique != nil && *fmq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range fmq.modifiers {
		m(selector)
	}
	for _, p := range fmq.predicates {
		p(selector)
	}
	for _, p := range fmq.order {
		p(selector)
	}
	if offset := fmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (fmq *FeedbackMessageQuery) ForUpdate(opts ...sql.LockOption) *FeedbackMessageQuery {
	if fmq.driver.Dialect() == dialect.Postgres {
		fmq.Unique(false)
	}
	fmq.modifiers = append(fmq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return fmq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (fmq *FeedbackMessageQuery) ForShare(opts ...sql.LockOption) *FeedbackMessageQuery {
	if fmq.driver.Dialect() == dialect.Postgres {
		fmq.Unique(false)
	}
	fmq.modifiers = append(fmq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return fmq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (fmq *FeedbackMessageQuery) Modify(modifiers ...func(s *sql.Selector)) *FeedbackMessageSelect {
	fmq.modifiers = append(fmq.modifiers, modifiers...)
	return fmq.Select()
}

// FeedbackMessageGroupBy is the group-by builder for FeedbackMessage entities.
type FeedbackMessageGroupBy struct {
	selector
	build *FeedbackMessageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fmgb *FeedbackMessageGroupBy) Aggregate(fns ...AggregateFunc) *FeedbackMessageGroupBy {
	fmgb.fns = append(fmgb.fns, fns...)
	return fmgb
}

// Scan applies the selector query and scans the result into the given value.
func (fmgb *FeedbackMessageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fmgb.build.ctx, ent.OpQueryGroupBy)
	if err := fmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FeedbackMessageQuery, *FeedbackMessageGroupBy](ctx, fmgb.build, fmgb, fmgb.build.inters, v)
}

func (fmgb *FeedbackMessageGroupBy) sqlScan(ctx context.Context, root *FeedbackMessageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fmgb.fns))
	for _, fn := range fmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fmgb.flds)+len(fmgb.fns))
		for _, f := range *fmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FeedbackMessageSelect is the builder for selecting fields of FeedbackMessage entities.
type FeedbackMessageSelect struct {
	*FeedbackMessageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fms *FeedbackMessageSelect) Aggregate(fns ...AggregateFunc) *FeedbackMessageSelect {
	fms.fns = append(fms.fns, fns...)
	return fms
}

// Scan applies the selector query and scans the result into the given value.
func (fms *FeedbackMessageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fms.ctx, ent.OpQuerySelect)
	if err := fms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FeedbackMessageQuery, *FeedbackMessageSelect](ctx, fms.FeedbackMessageQuery, fms, fms.inters, v)
}

func (fms *FeedbackMessageSelect) sqlScan(ctx context.Context, root *FeedbackMessageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fms.fns))
	for _, fn := range fms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (fms *FeedbackMessageSelect) Modify(modifiers ...func(s *sql.Selector)) *FeedbackMessageSelect {
	fms.modifiers = append(fms.modifiers, modifiers...)
	return fms
}
