// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"registry-backend/ent/node"
	"registry-backend/ent/personalaccesstoken"
	"registry-backend/ent/predicate"
	"registry-backend/ent/publisher"
	"registry-backend/ent/publisherpermission"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PublisherQuery is the builder for querying Publisher entities.
type PublisherQuery struct {
	config
	ctx                      *QueryContext
	order                    []publisher.OrderOption
	inters                   []Interceptor
	predicates               []predicate.Publisher
	withPublisherPermissions *PublisherPermissionQuery
	withNodes                *NodeQuery
	withPersonalAccessTokens *PersonalAccessTokenQuery
	modifiers                []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PublisherQuery builder.
func (pq *PublisherQuery) Where(ps ...predicate.Publisher) *PublisherQuery {
	pq.predicates = append(pq.predicates, ps...)
	return pq
}

// Limit the number of records to be returned by this query.
func (pq *PublisherQuery) Limit(limit int) *PublisherQuery {
	pq.ctx.Limit = &limit
	return pq
}

// Offset to start from.
func (pq *PublisherQuery) Offset(offset int) *PublisherQuery {
	pq.ctx.Offset = &offset
	return pq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pq *PublisherQuery) Unique(unique bool) *PublisherQuery {
	pq.ctx.Unique = &unique
	return pq
}

// Order specifies how the records should be ordered.
func (pq *PublisherQuery) Order(o ...publisher.OrderOption) *PublisherQuery {
	pq.order = append(pq.order, o...)
	return pq
}

// QueryPublisherPermissions chains the current query on the "publisher_permissions" edge.
func (pq *PublisherQuery) QueryPublisherPermissions() *PublisherPermissionQuery {
	query := (&PublisherPermissionClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(publisher.Table, publisher.FieldID, selector),
			sqlgraph.To(publisherpermission.Table, publisherpermission.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, publisher.PublisherPermissionsTable, publisher.PublisherPermissionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNodes chains the current query on the "nodes" edge.
func (pq *PublisherQuery) QueryNodes() *NodeQuery {
	query := (&NodeClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(publisher.Table, publisher.FieldID, selector),
			sqlgraph.To(node.Table, node.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, publisher.NodesTable, publisher.NodesColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPersonalAccessTokens chains the current query on the "personal_access_tokens" edge.
func (pq *PublisherQuery) QueryPersonalAccessTokens() *PersonalAccessTokenQuery {
	query := (&PersonalAccessTokenClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(publisher.Table, publisher.FieldID, selector),
			sqlgraph.To(personalaccesstoken.Table, personalaccesstoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, publisher.PersonalAccessTokensTable, publisher.PersonalAccessTokensColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Publisher entity from the query.
// Returns a *NotFoundError when no Publisher was found.
func (pq *PublisherQuery) First(ctx context.Context) (*Publisher, error) {
	nodes, err := pq.Limit(1).All(setContextOp(ctx, pq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{publisher.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pq *PublisherQuery) FirstX(ctx context.Context) *Publisher {
	node, err := pq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Publisher ID from the query.
// Returns a *NotFoundError when no Publisher ID was found.
func (pq *PublisherQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = pq.Limit(1).IDs(setContextOp(ctx, pq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{publisher.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pq *PublisherQuery) FirstIDX(ctx context.Context) string {
	id, err := pq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Publisher entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Publisher entity is found.
// Returns a *NotFoundError when no Publisher entities are found.
func (pq *PublisherQuery) Only(ctx context.Context) (*Publisher, error) {
	nodes, err := pq.Limit(2).All(setContextOp(ctx, pq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{publisher.Label}
	default:
		return nil, &NotSingularError{publisher.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pq *PublisherQuery) OnlyX(ctx context.Context) *Publisher {
	node, err := pq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Publisher ID in the query.
// Returns a *NotSingularError when more than one Publisher ID is found.
// Returns a *NotFoundError when no entities are found.
func (pq *PublisherQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = pq.Limit(2).IDs(setContextOp(ctx, pq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{publisher.Label}
	default:
		err = &NotSingularError{publisher.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pq *PublisherQuery) OnlyIDX(ctx context.Context) string {
	id, err := pq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Publishers.
func (pq *PublisherQuery) All(ctx context.Context) ([]*Publisher, error) {
	ctx = setContextOp(ctx, pq.ctx, "All")
	if err := pq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Publisher, *PublisherQuery]()
	return withInterceptors[[]*Publisher](ctx, pq, qr, pq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pq *PublisherQuery) AllX(ctx context.Context) []*Publisher {
	nodes, err := pq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Publisher IDs.
func (pq *PublisherQuery) IDs(ctx context.Context) (ids []string, err error) {
	if pq.ctx.Unique == nil && pq.path != nil {
		pq.Unique(true)
	}
	ctx = setContextOp(ctx, pq.ctx, "IDs")
	if err = pq.Select(publisher.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pq *PublisherQuery) IDsX(ctx context.Context) []string {
	ids, err := pq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pq *PublisherQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pq.ctx, "Count")
	if err := pq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pq, querierCount[*PublisherQuery](), pq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pq *PublisherQuery) CountX(ctx context.Context) int {
	count, err := pq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pq *PublisherQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pq.ctx, "Exist")
	switch _, err := pq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pq *PublisherQuery) ExistX(ctx context.Context) bool {
	exist, err := pq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PublisherQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pq *PublisherQuery) Clone() *PublisherQuery {
	if pq == nil {
		return nil
	}
	return &PublisherQuery{
		config:                   pq.config,
		ctx:                      pq.ctx.Clone(),
		order:                    append([]publisher.OrderOption{}, pq.order...),
		inters:                   append([]Interceptor{}, pq.inters...),
		predicates:               append([]predicate.Publisher{}, pq.predicates...),
		withPublisherPermissions: pq.withPublisherPermissions.Clone(),
		withNodes:                pq.withNodes.Clone(),
		withPersonalAccessTokens: pq.withPersonalAccessTokens.Clone(),
		// clone intermediate query.
		sql:  pq.sql.Clone(),
		path: pq.path,
	}
}

// WithPublisherPermissions tells the query-builder to eager-load the nodes that are connected to
// the "publisher_permissions" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PublisherQuery) WithPublisherPermissions(opts ...func(*PublisherPermissionQuery)) *PublisherQuery {
	query := (&PublisherPermissionClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withPublisherPermissions = query
	return pq
}

// WithNodes tells the query-builder to eager-load the nodes that are connected to
// the "nodes" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PublisherQuery) WithNodes(opts ...func(*NodeQuery)) *PublisherQuery {
	query := (&NodeClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withNodes = query
	return pq
}

// WithPersonalAccessTokens tells the query-builder to eager-load the nodes that are connected to
// the "personal_access_tokens" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PublisherQuery) WithPersonalAccessTokens(opts ...func(*PersonalAccessTokenQuery)) *PublisherQuery {
	query := (&PersonalAccessTokenClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withPersonalAccessTokens = query
	return pq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Publisher.Query().
//		GroupBy(publisher.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pq *PublisherQuery) GroupBy(field string, fields ...string) *PublisherGroupBy {
	pq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PublisherGroupBy{build: pq}
	grbuild.flds = &pq.ctx.Fields
	grbuild.label = publisher.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.Publisher.Query().
//		Select(publisher.FieldCreateTime).
//		Scan(ctx, &v)
func (pq *PublisherQuery) Select(fields ...string) *PublisherSelect {
	pq.ctx.Fields = append(pq.ctx.Fields, fields...)
	sbuild := &PublisherSelect{PublisherQuery: pq}
	sbuild.label = publisher.Label
	sbuild.flds, sbuild.scan = &pq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PublisherSelect configured with the given aggregations.
func (pq *PublisherQuery) Aggregate(fns ...AggregateFunc) *PublisherSelect {
	return pq.Select().Aggregate(fns...)
}

func (pq *PublisherQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pq); err != nil {
				return err
			}
		}
	}
	for _, f := range pq.ctx.Fields {
		if !publisher.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pq.path != nil {
		prev, err := pq.path(ctx)
		if err != nil {
			return err
		}
		pq.sql = prev
	}
	return nil
}

func (pq *PublisherQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Publisher, error) {
	var (
		nodes       = []*Publisher{}
		_spec       = pq.querySpec()
		loadedTypes = [3]bool{
			pq.withPublisherPermissions != nil,
			pq.withNodes != nil,
			pq.withPersonalAccessTokens != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Publisher).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Publisher{config: pq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(pq.modifiers) > 0 {
		_spec.Modifiers = pq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pq.withPublisherPermissions; query != nil {
		if err := pq.loadPublisherPermissions(ctx, query, nodes,
			func(n *Publisher) { n.Edges.PublisherPermissions = []*PublisherPermission{} },
			func(n *Publisher, e *PublisherPermission) {
				n.Edges.PublisherPermissions = append(n.Edges.PublisherPermissions, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := pq.withNodes; query != nil {
		if err := pq.loadNodes(ctx, query, nodes,
			func(n *Publisher) { n.Edges.Nodes = []*Node{} },
			func(n *Publisher, e *Node) { n.Edges.Nodes = append(n.Edges.Nodes, e) }); err != nil {
			return nil, err
		}
	}
	if query := pq.withPersonalAccessTokens; query != nil {
		if err := pq.loadPersonalAccessTokens(ctx, query, nodes,
			func(n *Publisher) { n.Edges.PersonalAccessTokens = []*PersonalAccessToken{} },
			func(n *Publisher, e *PersonalAccessToken) {
				n.Edges.PersonalAccessTokens = append(n.Edges.PersonalAccessTokens, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pq *PublisherQuery) loadPublisherPermissions(ctx context.Context, query *PublisherPermissionQuery, nodes []*Publisher, init func(*Publisher), assign func(*Publisher, *PublisherPermission)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Publisher)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(publisherpermission.FieldPublisherID)
	}
	query.Where(predicate.PublisherPermission(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(publisher.PublisherPermissionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PublisherID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "publisher_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (pq *PublisherQuery) loadNodes(ctx context.Context, query *NodeQuery, nodes []*Publisher, init func(*Publisher), assign func(*Publisher, *Node)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Publisher)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(node.FieldPublisherID)
	}
	query.Where(predicate.Node(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(publisher.NodesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PublisherID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "publisher_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (pq *PublisherQuery) loadPersonalAccessTokens(ctx context.Context, query *PersonalAccessTokenQuery, nodes []*Publisher, init func(*Publisher), assign func(*Publisher, *PersonalAccessToken)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Publisher)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(personalaccesstoken.FieldPublisherID)
	}
	query.Where(predicate.PersonalAccessToken(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(publisher.PersonalAccessTokensColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PublisherID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "publisher_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (pq *PublisherQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pq.querySpec()
	if len(pq.modifiers) > 0 {
		_spec.Modifiers = pq.modifiers
	}
	_spec.Node.Columns = pq.ctx.Fields
	if len(pq.ctx.Fields) > 0 {
		_spec.Unique = pq.ctx.Unique != nil && *pq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pq.driver, _spec)
}

func (pq *PublisherQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(publisher.Table, publisher.Columns, sqlgraph.NewFieldSpec(publisher.FieldID, field.TypeString))
	_spec.From = pq.sql
	if unique := pq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pq.path != nil {
		_spec.Unique = true
	}
	if fields := pq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, publisher.FieldID)
		for i := range fields {
			if fields[i] != publisher.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pq *PublisherQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pq.driver.Dialect())
	t1 := builder.Table(publisher.Table)
	columns := pq.ctx.Fields
	if len(columns) == 0 {
		columns = publisher.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pq.sql != nil {
		selector = pq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pq.ctx.Unique != nil && *pq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range pq.modifiers {
		m(selector)
	}
	for _, p := range pq.predicates {
		p(selector)
	}
	for _, p := range pq.order {
		p(selector)
	}
	if offset := pq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (pq *PublisherQuery) ForUpdate(opts ...sql.LockOption) *PublisherQuery {
	if pq.driver.Dialect() == dialect.Postgres {
		pq.Unique(false)
	}
	pq.modifiers = append(pq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return pq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (pq *PublisherQuery) ForShare(opts ...sql.LockOption) *PublisherQuery {
	if pq.driver.Dialect() == dialect.Postgres {
		pq.Unique(false)
	}
	pq.modifiers = append(pq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return pq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (pq *PublisherQuery) Modify(modifiers ...func(s *sql.Selector)) *PublisherSelect {
	pq.modifiers = append(pq.modifiers, modifiers...)
	return pq.Select()
}

// PublisherGroupBy is the group-by builder for Publisher entities.
type PublisherGroupBy struct {
	selector
	build *PublisherQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pgb *PublisherGroupBy) Aggregate(fns ...AggregateFunc) *PublisherGroupBy {
	pgb.fns = append(pgb.fns, fns...)
	return pgb
}

// Scan applies the selector query and scans the result into the given value.
func (pgb *PublisherGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pgb.build.ctx, "GroupBy")
	if err := pgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublisherQuery, *PublisherGroupBy](ctx, pgb.build, pgb, pgb.build.inters, v)
}

func (pgb *PublisherGroupBy) sqlScan(ctx context.Context, root *PublisherQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pgb.fns))
	for _, fn := range pgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pgb.flds)+len(pgb.fns))
		for _, f := range *pgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PublisherSelect is the builder for selecting fields of Publisher entities.
type PublisherSelect struct {
	*PublisherQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ps *PublisherSelect) Aggregate(fns ...AggregateFunc) *PublisherSelect {
	ps.fns = append(ps.fns, fns...)
	return ps
}

// Scan applies the selector query and scans the result into the given value.
func (ps *PublisherSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ps.ctx, "Select")
	if err := ps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublisherQuery, *PublisherSelect](ctx, ps.PublisherQuery, ps, ps.inters, v)
}

func (ps *PublisherSelect) sqlScan(ctx context.Context, root *PublisherQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ps.fns))
	for _, fn := range ps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ps *PublisherSelect) Modify(modifiers ...func(s *sql.Selector)) *PublisherSelect {
	ps.modifiers = append(ps.modifiers, modifiers...)
	return ps
}
