// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CIWorkflowResult is the predicate function for ciworkflowresult builders.
type CIWorkflowResult func(*sql.Selector)

// GitCommit is the predicate function for gitcommit builders.
type GitCommit func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// NodeReview is the predicate function for nodereview builders.
type NodeReview func(*sql.Selector)

// NodeVersion is the predicate function for nodeversion builders.
type NodeVersion func(*sql.Selector)

// PersonalAccessToken is the predicate function for personalaccesstoken builders.
type PersonalAccessToken func(*sql.Selector)

// Publisher is the predicate function for publisher builders.
type Publisher func(*sql.Selector)

// PublisherPermission is the predicate function for publisherpermission builders.
type PublisherPermission func(*sql.Selector)

// StorageFile is the predicate function for storagefile builders.
type StorageFile func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
